spring:
  application:
      name: websocket-project
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  profiles:
    active: dev